### ISSUE TITLE
Error1 Message?

### ISSUE THREAD

**Issue by Kidazpan** [N3Roaster/typica#133]
![capture](https://cloud.githubusercontent.com/assets/10430484/5812538/13d36624-a0c1-11e4-83e5-5e18a32ad112.PNG)

I bought a DATAQ DI-145 to try and also made a same setup like you set on Youtube with my Diedrich IR-1.

After Click on "Roast Coffee" Button is shows Error1 : An error occurs.(photo attached)

Any Suggestions?

Warm Regards,Ed.

**Comment by N3Roaster** [comment]
To use the DATAQ DI-145 it is necessary to install the DATAQ SDK [as documented for that hardware](http://www.randomfield.com/programs/typica/documentation/appendix-a.5.html) which provides a set of libraries and executables that Typica uses to communicate with that hardware. That particular error code indicates a failure to load the appropriate library. The most likely explanation is that simply isn't installed.

If it is installed then the next possibility is that the assigned port number for the device doesn't match with the available libraries. The DATAQ SDK is rather unusual in this regard as instead of having a single library that should be used regardless of the port number, it ships several DI1xxNT.DLL files where xx corresponds to the port number (with leading 0 for single digit port numbers). For example, if the device is assigned to COM12, it's recommended to load DI112NT.DLL, but DATAQ Instruments does not ship such files for all possible port numbers. An immediate workaround in this case would be to see which DLLs exist and manually set the port number to something appropriate.

If it turns out to be the case that the SDK is installed and the assigned port is out of range, I'd like to know that. While the DATAQ SDK documentation recommends loading a DLL corresponding to the port number, I've tested that this is not strictly required and that it works to just load whatever and make the (required regardless) API call to set the correct port. In this case the process started by the library won't have a name matching the port number in the task manager, but that's a cosmetic issue rather than a functional one.

Please let me know regardless of which of these is true so I can decide an appropriate disposition for the opened issue.

**Comment by Kidazpan** [comment]
Thank a lots Neal. I solved this problem but still have another problem
coming up.

1. I am watching your video on youtube "
Data Acquisition with the Diedrich IR-1 Profile Lab Roaster - Coffee
Roasting
​"
Could you please downloaded attached photo?​
​Thank you Niel! You are the best man that I ever know!
[image: Inline image 3][image: Inline image 2]​


Kind Regards,

*Eddy Pan*
Account Manager | Ph 02 9550 2222 | Mob 0410 516 456
Voodoo Coffee Company | Home to Sacred Grounds
www.voodooespresso.com | www.sacredgroundsorganic.com



<https://www.facebook.com/pages/Sacred-Grounds-Organic-and-Fairtrade/124752877661>
   <https://twitter.com/Sacred_Grounds_>
<http://sacredgroundsorganic.wordpress.com/>
<http://www.pinterest.com/sacredgroundsco/>
<http://instagram.com/sacred_grounds_>
<https://plus.google.com/u/0/b/107737910666853440549/107737910666853440549/posts/p/pub>

This message contains information that is confidential.  If you are not the
intended recipient, you must not use, disseminate or copy this message.  If
you have received this message in error, please notify us immediately and
destroy the original message.  Thank you.

**Comment by N3Roaster** [comment]
Github seems to strip image attachments from email replies so I don't have those. It might be better to take this to email. I can be reached at roaster@wilsonscoffee.com. Given that this doesn't appear to be an issue with Typica I'm closing the issue.

PS: Your message went to a public web site where the confidentiality boilerplate looks rather silly. You might want to be a little more careful with that in the future.
